{% set version = "2.1.0" %}

package:
  name: django-ajax-selects
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-ajax-selects/django-ajax-selects-{{ version }}.tar.gz
  sha256: d35a386d6bfc61b45a22de9648237df7f750dd37abf50203bbd694d03460397b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django

test:
  imports:
    - ajax_select
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/crucialfelix/django-ajax-selects/
  license: MIT
  license_file: LICENSE
  summary: Edit ForeignKey, ManyToManyField and CharField in Django Admin using jQuery UI AutoComplete.

extra:
  recipe-maintainers:
    - ocefpaf
