{% set python_min = '3.10.0' %}
{% set name = "django-ajax-selects" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_ajax_selects-{{ version }}.tar.gz
  sha256: 650071c78c333139059e00a41e9aeff21234e026f2076965429594f5c5327f35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - django >=3.2

test:
  imports:
    - ajax_select
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/crucialfelix/django-ajax-selects/
  license: MIT AND GPL-3.0-or-later
  license_file: LICENSE
  summary: Edit ForeignKey, ManyToManyField and CharField in Django Admin using jQuery UI AutoComplete.

extra:
  recipe-maintainers:
    - ocefpaf
