{% set version = "3.0.2" %}

package:
  name: django-ajax-selects
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-ajax-selects/django_ajax_selects-{{ version }}.tar.gz
  sha256: 8554659f5c7da50cfe1f0d0e14c6f360d0f2ab2d94b24e3203cc4fe974bd945a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django >=3,<=4

test:
  imports:
    - ajax_select
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/crucialfelix/django-ajax-selects/
  license: MIT
  license_file: LICENSE
  summary: Edit ForeignKey, ManyToManyField and CharField in Django Admin using jQuery UI AutoComplete.

extra:
  recipe-maintainers:
    - ocefpaf
