{% set version = "2.2.0" %}

package:
  name: django-ajax-selects
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-ajax-selects/django-ajax-selects-{{ version }}.tar.gz
  sha256: 539298874b2d26ce9e778a5173d312f55340c887a126c7e2d3460b9a5b4593a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django >=3,<=4

test:
  imports:
    - ajax_select
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/crucialfelix/django-ajax-selects/
  license: MIT
  license_file: LICENSE
  summary: Edit ForeignKey, ManyToManyField and CharField in Django Admin using jQuery UI AutoComplete.

extra:
  recipe-maintainers:
    - ocefpaf
